services:
  fastapi-otel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-otel
    ports:
      - "8000:8000"
    environment:
      OTEL_METRIC_EXPORT_INTERVAL: "5000"
      OTEL_SERVICE_NAME: "fastapi-otel"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4317"
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
